# fly.toml app configuration file generated for harvest-hero-pantry on 2026-09-08T16:25:35-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'harvest-hero-pantry'
primary_region = 'iad'

[build]
  dockerfile = 'Dockerfile'

[env]
  HARVESTHERO_COOKIE_SECURE = '1'
  HARVESTHERO_DEV_DIR = '/data'
  PORT = '8080'

[[mounts]]
  source = 'harvest_data'
  destination = '/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 0

  [[http_service.checks]]
    interval = '15s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/healthz'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
