"""Session-hardening helpers.

Three invariants enforced here:

1. **Session-fixation defense.** After a successful login, the session
   ID is regenerated by clearing and repopulating the session dict.
   Flask's default cookie-based session means the client gets a new
   signed cookie value on the login response, so anything an
   attacker pre-planted is invalidated.

2. **Global logout on password change.** At login we snapshot the
   current password_hash prefix into the session. The
   ``check_session_still_valid`` before-request hook re-reads the
   user's password_hash and compares. If it changed (i.e. the user
   or an admin rotated the password), every session that predates
   the change fails the comparison and is logged out.

3. **Idle timeout.** Every request refreshes ``session["last_seen"]``.
   If a request arrives after ``IDLE_TIMEOUT_SECONDS`` of no activity,
   the session is cleared and Flask-Login kicks the user back to
   /login.

Register the before-request hook exactly once from ``create_app``:

    from security import install_session_guards
    install_session_guards(app)

Call ``mark_login(user_row)`` from the login route after
``login_user(...)`` succeeds.
"""

from __future__ import annotations

import time

from flask import redirect, session, url_for
from flask_login import current_user, logout_user


# 30 minutes of inactivity → forced logout. Independent of the
# absolute 12h session lifetime configured in Config.
IDLE_TIMEOUT_SECONDS = 30 * 60


def mark_login(user_row: dict) -> None:
    """Called from the login handler after ``login_user`` succeeds.

    Rotates the session ID and stamps identifiers we later use for
    invariant checks. Safe to call multiple times.
    """
    # Snapshot the current pw-hash prefix so a later password change
    # by anyone (self, admin) invalidates this session.
    pw_hash = user_row.get("password_hash") or ""
    session["_pw_prefix"] = pw_hash[:32]
    session["_uid"]       = user_row.get("id")
    session["last_seen"]  = int(time.time())
    # Force Flask to send a fresh Set-Cookie header with the new
    # signed payload — session-fixation defense.
    session.modified = True


def refresh_pw_prefix(new_password_hash: str) -> None:
    """Called after a successful password change by the current user.

    Updates the stored pw-hash prefix so THIS session stays valid;
    every OTHER session (still holding the old prefix) will be
    kicked out by the before-request guard on their next request.
    """
    session["_pw_prefix"] = (new_password_hash or "")[:32]
    session.modified = True


def _clear_and_kick():
    """Log the user out and redirect to /login. Used by the
    before-request guard when the session is stale."""
    logout_user()
    session.clear()
    return redirect(url_for("auth.login"))


def install_session_guards(app) -> None:
    """Wire the before-request hook that enforces invariants 2 and 3."""

    @app.before_request
    def _session_guards():
        if not current_user.is_authenticated:
            return None

        # Idle timeout.
        now = int(time.time())
        last = int(session.get("last_seen") or 0)
        if last and (now - last) > IDLE_TIMEOUT_SECONDS:
            return _clear_and_kick()
        session["last_seen"] = now

        # Password-changed-elsewhere check.
        stored_prefix = session.get("_pw_prefix")
        if stored_prefix is None:
            # Legacy session predating this deploy — force reauth so
            # every logged-in user gets stamped fresh.
            return _clear_and_kick()

        # Look up the current pw hash. Import locally to avoid a
        # circular import with routes.auth at module load time.
        from database import Database
        row = Database().get_user(current_user.username)
        if not row or not row.get("is_active"):
            return _clear_and_kick()

        current_prefix = (row.get("password_hash") or "")[:32]
        if current_prefix != stored_prefix:
            return _clear_and_kick()

        return None
